.\"  -*- nroff -*-
.\"
.\" testkeys.1
.\"
.\" Man page created from source and usage information
.\" Cesare Falco <cesare.falco@gmail.com>, February 2007
.\"
.TH TESTKEYS 1 2012-03-25 0.145u5 "testkeys"
.\"
.\" NAME chapter
.SH NAME
testkeys \- returns SDL keycode for key pressed.
.\"
.\" SYNOPSIS chapter
.SH SYNOPSIS
.B testkeys
.\"
.\" DESCRIPTION chapter
.SH DESCRIPTION
Since 0.113 SDLMAME introduced keymap files to handle keyboards with non\-us layouts.
.PP
This simple utility helps determining which SDL keycode is bound to each key, thus
making the process of compiling keymap files a bit easier.
