# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

# Core definitions
.core-defs:
  variables:
    MAKEFILE: Makefile.libretro
    CORENAME: mame

# Core definitions
include:
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
    
  # # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-make.yml'

  # # Nintendo 3DS
  # - project: 'libretro-infrastructure/ci-templates'
  #   file: '/ctr-static.yml'
    
  # # Nintendo WiiU
  # - project: 'libretro-infrastructure/ci-templates'
  #   file: '/wiiu-static.yml'

  # # Nintendo Switch
  # - project: 'libretro-infrastructure/ci-templates'
  #   file: '/libnx-static.yml'

  # # PlayStation Vita
  # - project: 'libretro-infrastructure/ci-templates'
  #   file: '/vita-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

# Cache
# Need to set a proper key in each job
cache: &global_cache
  untracked: true
  paths:
    - build/

# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
  cache:
    <<: *global_cache
    key: "$CI_COMMIT_REF_SLUG-windows-x64"

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs
  cache:
    <<: *global_cache
    key: "$CI_COMMIT_REF_SLUG-windows-i686"

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs
  cache:
    <<: *global_cache
    key: "$CI_COMMIT_REF_SLUG-linux-x64"

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs
  cache:
    <<: *global_cache
    key: "$CI_COMMIT_REF_SLUG-linux-i686"
    
# MacOS 64-bit
libretro-build-osx-x64:
  tags:
    - macosx-packaging
  extends:
    - .libretro-osx-x64-make-default
    - .core-defs
  cache:
    <<: *global_cache
    key: "$CI_COMMIT_REF_SLUG-osx-x64"

# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-make-armeabi-v7a
    - .core-defs
  variables:
    TARGET:    mame
    SUBTARGET: arcade
    CORENAME:  mamearcade
  cache:
    <<: *global_cache
    key: "$CI_COMMIT_REF_SLUG-android-armeabi-v7a"

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-make-arm64-v8a
    - .core-defs
  variables:
    TARGET:    mame
    SUBTARGET: arcade
    CORENAME:  mamearcade
  cache:
    <<: *global_cache
    key: "$CI_COMMIT_REF_SLUG-android-arm64-v8a"

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-make-x86_64
    - .core-defs
  variables:
    TARGET:    mame
    SUBTARGET: arcade
    CORENAME:  mamearcade
  cache:
    <<: *global_cache
    key: "$CI_COMMIT_REF_SLUG-android-x86_64"
    
# # Android 32-bit x86
# android-x86:
#   extends:
#     - .libretro-android-jni-x86
#     - .core-defs

# # Nintendo 3DS
# libretro-build-ctr:
#   extends:
#     - .libretro-ctr-static-retroarch-master
#     - .core-defs
    
# # Nintendo WiiU
# libretro-build-wiiu:
#   extends:
#     - .libretro-wiiu-static-retroarch-master
#     - .core-defs

# # Nintendo Switch
# libretro-build-libnx-aarch64:
#   extends:
#     - .libretro-libnx-static-retroarch-master
#     - .core-defs

# # PlayStation Vita
# libretro-build-vita:
#   extends:
#     - .libretro-vita-static-retroarch-master
#     - .core-defs
