name: Generate Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  doxygen:
    name: Doxygen
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends doxygen

      - name: Generate Documentation
        run: doxygen
        working-directory: .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
