BGFX_DIR=../../../../../../3rdparty/bgfx
RUNTIME_DIR=../../../../../..
BUILD_DIR=../../../../../../build

include $(BGFX_DIR)/scripts/shader.mk

rebuild:
	@make -s --no-print-directory TARGET=0 clean all
	@make -s --no-print-directory TARGET=1 clean all
	@make -s --no-print-directory TARGET=2 clean all
	@make -s --no-print-directory TARGET=3 clean all
	@make -s --no-print-directory TARGET=4 clean all
	@make -s --no-print-directory TARGET=5 clean all
