// license:GPL-2.0+
// copyright-holders:Felipe Sanches

// KN7000 front panel: matrix geometry and LED decode.

#include "emu.h"
#include "kn7000_cpanel.h"

#define LOG_LEDS (1U << 1)

#define VERBOSE 0
#include "logmacro.h"


DEFINE_DEVICE_TYPE(KN7000_CPANEL, kn7000_cpanel_device, "kn7000_cpanel", "KN7000 control panel")

namespace {

// The segment each scan port reports, in the order of the scan tags below: CPL
// columns 0-4, 6 and 7, CPC columns 5 and 8-11, then CPR columns 0-9
constexpr u8 PORT_SEG[22] = {
	0x00, 0x01, 0x02, 0x03, 0x04, 0x06, 0x07,
	0x05, 0x08, 0x09, 0x0a, 0x0b,
	0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15 };

// The wire address each segment is reported at
constexpr u8 SEG_WIRE_ADDR[22] = {
	0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xcb,
	0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09 };

INPUT_PORTS_START(kn7000_cpanel)
	PORT_START("CPL_SEG0")   // CPL scan column 0, segment 0x00 (wire address 0xc0)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDL 4 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDL 1 (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDL 5 (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDL 2 (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("START/STOP (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDL 3 (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("INTRO & ENDING 2 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SYNCHRO & BREAK (SW7)")
	PORT_START("CPL_SEG1")   // CPL scan column 1, segment 0x01 (wire address 0xc1)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("RHYTHM GROUP/MEMORY (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("ORGANIST (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("CUSTOM (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("ENTERTAINER (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LATIN & WORLD (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MOVIE & SHOW (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MARCH & WALTZ (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("BALLROOM (SW7)")
	PORT_START("CPL_SEG2")   // CPL scan column 2, segment 0x02 (wire address 0xc2)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("COUNTRY & WESTERN (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("JAZZ & SWING (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SOUL & R&B (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("BALLAD (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MODERN DANCE (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("ROCK & POP (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("60s & 70s (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("8 & 16 BEAT (SW7)")
	PORT_START("CPL_SEG3")   // CPL scan column 3, segment 0x03 (wire address 0xc3)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("INTRO & ENDING 1 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("TAP TEMPO (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("FILL IN 2 (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("FADE OUT (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("FILL IN 1 (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("FADE IN (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("VARIATION & MSA 4 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SPLIT POINT (SW7)")
	PORT_START("CPL_SEG4")   // CPL scan column 4, segment 0x04 (wire address 0xc4)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("VARIATION & MSA 3 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("ONE TOUCH PLAY (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("VARIATION & MSA 2 (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUSIC STYLE ARRANGER (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("VARIATION & MSA 1 (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PAD 3 (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PAD 6/SOLO (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PAD 2 (SW7)")
	PORT_START("CPL_SEG6")   // CPL scan column 6, segment 0x06 (wire address 0xc6)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PAD 5/SOLO (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PERFORMANCE PADS/STOP (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PAD 4 (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PERFORMANCE PADS/BANK (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PAD 1 (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PERFORMANCE PADS/AUTO SETTING (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("DEMO (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPL_SEG7")   // CPL scan column 7, segment 0x07 (wire address 0xc7)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUSIC STYLIST (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("AUTO PLAY CHORD MODE (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SOUND SET (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("AUTO PLAY CHORD OFF/ON (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("ARRANGER OFF/ON (SW4)")
	PORT_BIT(0xe0, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPC_SEG5")   // CPC scan column 5, segment 0x05 (wire address 0xc5)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("OTHER PART & FR (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("HELP (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("CONTRAST UP (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("CONTRAST DOWN (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 1 (PART 1 ON) (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 1 (PART 1 OFF) (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 2 (PART 2 ON) (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 2 (PART 2 OFF) (SW7)")
	PORT_START("CPC_SEG8")   // CPC scan column 8, segment 0x08 (wire address 0xc8)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 3 (PART 3 ON) (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 3 (PART 3 OFF) (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 4 (PART 4 ON) (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 4 (PART 4 OFF) (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 5 (PART 5 ON) (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 5 (PART 5 OFF) (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 6 (PART 6 ON) (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 6 (PART 6 OFF) (SW7)")
	PORT_START("CPC_SEG9")   // CPC scan column 9, segment 0x09 (wire address 0xc9)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 7 (PART 7 ON) (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 7 (PART 7 OFF) (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 8 (PART 8 ON) (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 8 (PART 8 OFF) (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 9 (PART 9 ON) (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 9 (PART 9 OFF) (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 10 (PART 10 ON) (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 10 (PART 10 OFF) (SW7)")
	PORT_START("CPC_SEG10")   // CPC scan column 10, segment 0x0a (wire address 0xca)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 11 (PART 11 ON) (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 11 (PART 11 OFF) (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 12 (PART 12 ON) (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 12 (PART 12 OFF) (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 13 (PART 13 ON) (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 13 (PART 13 OFF) (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 14 (PART 14 ON) (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 14 (PART 14 OFF) (SW7)")
	PORT_START("CPC_SEG11")   // CPC scan column 11, segment 0x0b (wire address 0xcb)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 15 (PART 15 ON) (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 15 (PART 15 OFF) (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE UP 16 (PART 16 ON) (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MUTE DOWN 16 (PART 16 OFF) (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PAGE UP (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PAGE DOWN (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("DISPLAY HOLD (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("EXIT (SW7)")
	PORT_START("CPR_SEG0")   // CPR scan column 0, segment 0x0c (wire address 0x00)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SOLO (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PANEL MEMORY 1 (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PROGRAM MENUS (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SEQUENCER EASY REC (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("STRINGS & VOCAL (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SYNTH (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("CUSTOMIZE (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPR_SEG1")   // CPR scan column 1, segment 0x0d (wire address 0x01)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("TECHNI-CHORD (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PART SELECT RIGHT 1 (SW1)")   // panel silk: RIGHT 1 (schematic mislabels this D1069 as LEFT)
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("DISK MENU LOAD (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SEQUENCER PLAY (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("WORLD (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PAD (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("CUSTOM PANEL (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SD CARD LOAD (SW7)")
	PORT_START("CPR_SEG2")   // CPR scan column 2, segment 0x0e (wire address 0x02)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PART SELECT LEFT (SW0)")   // panel silk: LEFT (schematic mislabels this D1055 as RIGHT 1)
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PART SELECT RIGHT 2 (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("EFFECT MIC (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("VARIATION (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MALLET & ORCH PERC (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("ACCORDION REGISTER (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("FAVORITES (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPR_SEG3")   // CPR scan column 3, segment 0x0f (wire address 0x03)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("TRANSPOSE + (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("CONDUCTOR RIGHT 1 (SW1)")   // panel silk: RIGHT 1 (schematic mislabels this D1107 as RIGHT 2)
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("REVERB (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SOUND DSP (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("GUITAR (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("ORGAN TABS (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PANEL MEMORY 5 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("NEXT BANK (SW7)")
	PORT_START("CPR_SEG4")   // CPR scan column 4, segment 0x10 (wire address 0x04)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("TRANSPOSE - (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("CONDUCTOR RIGHT 2 (SW1)")   // panel silk: RIGHT 2 (schematic mislabels this D1114 as RIGHT 1)
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("MULTI (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("DIGITAL EFFECT (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PIANO (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("DIGITAL DRAWBAR (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PANEL MEMORY 4 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("BANK VIEW (PANEL MEMORY BANK SELECT) (SW7)")
	PORT_START("CPR_SEG5")   // CPR scan column 5, segment 0x11 (wire address 0x05)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDR 5 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("CONDUCTOR LEFT (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("CHORUS (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SUSTAIN (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDR 1 (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDR 2 (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PANEL MEMORY 3 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PANEL MEMORY 6 (SW7)")
	PORT_START("CPR_SEG6")   // CPR scan column 6, segment 0x12 (wire address 0x06)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDR 4 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("R1/R2 OCTAVE + (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("EW EXPANSION (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SOUND EXPLORER (SW3)")
	PORT_BIT(0x30, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PANEL MEMORY 2 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PANEL MEMORY 7 (SW7)")
	PORT_START("CPR_SEG7")   // CPR scan column 7, segment 0x13 (wire address 0x07)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("LCDR 3 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("R1/R2 OCTAVE - (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SOUND GROUP/MEMORY (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("ORGAN & ACCORDION (SW3)")
	PORT_BIT(0x30, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PANEL MEMORY SET (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("PANEL MEMORY 8 (SW7)")
	PORT_START("CPR_SEG8")   // CPR scan column 8, segment 0x14 (wire address 0x08)
	PORT_BIT(0x03, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("DRUM KITS (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SAX & WOODWIND (SW3)")
	PORT_BIT(0xf0, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPR_SEG9")   // CPR scan column 9, segment 0x15 (wire address 0x09)
	PORT_BIT(0x03, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("BASS (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("BRASS (SW3)")
	PORT_BIT(0xf0, IP_ACTIVE_HIGH, IPT_UNUSED)
INPUT_PORTS_END

} // anonymous namespace

ioport_constructor kn7000_cpanel_device::device_input_ports() const
{
	return INPUT_PORTS_NAME(kn7000_cpanel);
}

kn7000_cpanel_device::kn7000_cpanel_device(const machine_config &mconfig, const char *tag, device_t *owner, u32 clock)
	: kn_cpanel_base_device(mconfig, KN7000_CPANEL, tag, owner, clock,
			{ "CPL_SEG0", "CPL_SEG1", "CPL_SEG2", "CPL_SEG3", "CPL_SEG4", "CPL_SEG6", "CPL_SEG7",
				"CPC_SEG5", "CPC_SEG8", "CPC_SEG9", "CPC_SEG10", "CPC_SEG11",
				"CPR_SEG0", "CPR_SEG1", "CPR_SEG2", "CPR_SEG3", "CPR_SEG4", "CPR_SEG5", "CPR_SEG6", "CPR_SEG7", "CPR_SEG8", "CPR_SEG9" },
			PORT_SEG, SEG_WIRE_ADDR)
	, m_cpl_leds(*this, "cpl_led%u", 0U)
	, m_cpc_leds(*this, "cpc_led%u", 0U)
	, m_cpr_leds(*this, "cpr_led%u", 0U)
{
}

// Register addresses 0x00-0x3f are the CPR board's, 0xe1-0xff the CPC board's,
// and the rest the CPL board's. 0xe0 is a sync code, so CPC register 0 is never
// written. The schematic designators, bits 0-7 of each register ("-": not
// identified):
//
// CPR
//   00: D1009 D1023 D1037 D1051 D1065 D1079 D1093 D1107
//   01: -     D1024 -     D1052 D1066 D1080 D1094 D1108
//   02: D1011 D1025 D1039 D1053 D1067 D1081 D1095 D1116
//   03: D1012 D1026 D1040 D1068 D1054 D1082 D1096 D1110
//   04: D1027 D1013 D1069 D1041 D1055 D1083 D1097 D1111
//   05: D1042 D1122 D1014 D1056 D1070 D1098 D1112 D1117
//   08: D1114 D1120 -     -     -     -     -     -
//   09: D1115 -     -     -     -     -     -     -
//   0a: D1109 D1028 -     -     -     -     -     -
//   0b: D1123 D1084 -     -     -     -     -     -
//   0c: D1118 -     -     -     -     -     -     -
//   0d: D1119 D1121 -     -     -     -     -     -
//
// CPL
//   00: D1116 D1147 -     D1164 D1180 -     -     -
//   01: D1115 D1142 -     D1163 D1179 -     -     -
//   02: D1114 D1141 D1130 D1162 D1178 -     -     -
//   03: -     D1145 D1148 D1161 D1177 -     -     -
//   04: -     D1143 D1128 D1160 D1176 -     -     -
//   05: -     D1127 D1126 D1159 D1175 -     -     -
//   06: -     -     D1129 D1158 D1174 -     -     -
//   07: -     D1125 D1144 D1157 D1173 -     -     -
void kn7000_cpanel_device::panel_led_frame(u8 addr, u8 data)
{
	if ((addr & 0xc0) == 0)
		set_led_reg(m_cpr_leds, addr & 0x3f, data);
	else if (addr >= 0xe1)
		set_led_reg(m_cpc_leds, addr & 0x1f, data);
	else
		set_led_reg(m_cpl_leds, addr & 0x3f, data);
	LOGMASKED(LOG_LEDS, "LED frame addr=%02X data=%02X\n", addr, data);
}
