INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);

INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_SS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);

INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);

INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_SS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);

INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);

INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_NSS_ST(INT32 SSS, INT32 SST, TILE* tex_tile);

INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);

INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);
INLINE UINT32 TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_NSS_NST(INT32 SSS, INT32 SST, TILE* tex_tile);

static UINT32 (*rdp_texture_pipeline_func[128])(INT32, INT32, TILE*) =
{
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_NSS_NST, TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_NDOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_NSS_NST, TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_NDOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_NSS_NST,  TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_NDOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_NSS_NST,  TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_NDOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_NSS_NST,  TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_NDOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_NSS_NST,  TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_NDOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_NSS_NST,   TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_NDOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_NSS_NST,   TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_NDOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_NSS_NST,  TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_DOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_NSS_NST,  TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_DOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_NSS_NST,   TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_DOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_NSS_NST,   TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_DOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_NSS_NST,   TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_DOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_NSS_NST,   TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_DOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_NSS_NST,    TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_DOT_NSS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_NSS_NST,    TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_DOT_NSS_NST,

	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_SS_NST,  TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_NDOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_SS_NST,  TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_NDOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_SS_NST,   TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_NDOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_SS_NST,   TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_NDOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_SS_NST,   TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_NDOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_SS_NST,   TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_NDOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_SS_NST,    TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_NDOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_SS_NST,    TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_NDOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_SS_NST,   TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_DOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_SS_NST,   TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_DOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_SS_NST,    TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_DOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_SS_NST,    TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_DOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_SS_NST,    TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_DOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_SS_NST,    TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_DOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_SS_NST,     TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_DOT_SS_NST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_SS_NST,     TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_DOT_SS_NST,

	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_NSS_ST,  TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_NDOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_NSS_ST,  TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_NDOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_NSS_ST,   TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_NDOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_NSS_ST,   TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_NDOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_NSS_ST,   TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_NDOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_NSS_ST,   TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_NDOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_NSS_ST,    TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_NDOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_NSS_ST,    TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_NDOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_NSS_ST,   TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_DOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_NSS_ST,   TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_DOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_NSS_ST,    TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_DOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_NSS_ST,    TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_DOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_NSS_ST,    TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_DOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_NSS_ST,    TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_DOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_NSS_ST,     TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_DOT_NSS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_NSS_ST,     TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_DOT_NSS_ST,

	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_SS_ST,   TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_NDOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_NDOT_SS_ST,   TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_NDOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_SS_ST,    TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_NDOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_NDOT_SS_ST,    TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_NDOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_SS_ST,    TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_NDOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_NDOT_SS_ST,    TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_NDOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_SS_ST,     TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_NDOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_NDOT_SS_ST,     TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_NDOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_SS_ST,    TEXTURE_PIPELINE_BILINEAR_NMID_NC_NDOS_DOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_NDOS_DOT_SS_ST,    TEXTURE_PIPELINE_BILINEAR_MID_NC_NDOS_DOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_SS_ST,     TEXTURE_PIPELINE_BILINEAR_NMID_C_NDOS_DOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_NDOS_DOT_SS_ST,     TEXTURE_PIPELINE_BILINEAR_MID_C_NDOS_DOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_SS_ST,     TEXTURE_PIPELINE_BILINEAR_NMID_NC_DOS_DOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_NC_DOS_DOT_SS_ST,     TEXTURE_PIPELINE_BILINEAR_MID_NC_DOS_DOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_SS_ST,      TEXTURE_PIPELINE_BILINEAR_NMID_C_DOS_DOT_SS_ST,
	TEXTURE_PIPELINE_NEAREST_NMID_C_DOS_DOT_SS_ST,      TEXTURE_PIPELINE_BILINEAR_MID_C_DOS_DOT_SS_ST,
};
