.\"  -*- nroff -*-
.\"
.\" floptool.1
.\"
.\" Man page created from usage info
.\" Cesare Falco <c.falco@ubuntu.com>, April 2014
.\"
.\"
.TH FLOPTOOL 1 2015-07-22 0.164 "MESS Generic floppy manipulation tool"
.\"
.\"
.\" NAME chapter
.SH NAME
floptool \- MESS Generic floppy image manipulation tool
.\"
.\"
.\" SYNOPSIS chapter
.SH SYNOPSIS
.B floptool
.I option
.\"
.\"
.\" DESCRIPTION chapter
.SH DESCRIPTION
.B floptool
is a tool for the maintenance and manipulation of floppy disk
images that MESS users need to deal with.
.\"
.\"
.\" COMMANDS chapter
.SH COMMANDS
.TP
.B identify \fIinputfile\fR [\fIinputfile \fR... ]
Determine the format of a floppy disk image.
.TP
.B convert [\fIinputformat\fR|\fIauto\fR] \fIoutputformat inputfile outputfile
Convert a floppy disk image to a different format.
.\"
.\"
.\" EXAMPLES chapter
.SH EXAMPLES
.B floptool identify image.dsk
.\"
.\"
.\" SEE ALSO chapter
.SH SEE ALSO
mess(6)
