.\"  -*- nroff -*-
.\"
.\" jedutil.1
.\"
.\" Man page created from source and usage information
.\" Cesare Falco <c.falco@ubuntu.com>, February 2007
.\" 
.\" References
.\" http://aarongiles.com/?p=159
.\"
.TH JEDUTIL 1 2015-07-22 0.164 "MAME JEDEC file utilities"
.\"
.\" NAME chapter
.SH NAME
jedutil \- MAME JEDEC file utilities
.\"
.\" SYNOPSIS chapter
.SH SYNOPSIS
.B jedutil
.RI [ option ]
.\"
.\" DESCRIPTION chapter
.SH DESCRIPTION
Data for Programmable Logic Devices (PLDs) are usually stored in a format known
as JEDEC, basically a text file allowing insertion of further information by
programmers.
.PP
MAME uses a raw binary representation of the same data, in order to
achieve correct identification of PLD data through CRC and SHA1 algorithms
(i.e. with the \-romident option).
.PP
.B jedutil
provides an easy way to convert PLDs data between these two formats.
.\"
.\" OPTIONS chapter
.SH OPTIONS
.TP
.B \-convert \fIinputfile outputfile \fR[\fIfuses\fR]
Converts JEDEC data between file formats. Both .jed (JEDEC) and .pla
(Berkeley standard PLA) files can be converted to a .bin (binary) file,
while a binary file can be converted to a .jed file only.
.TP
.B \-view \fIinputfile device
Dump logic equations. \fIinputfile\fR can be either a JED or binary file.
.TP
.B \-viewlist
View list of supported devices.
.SH SEE ALSO
mame(6), mess(6)
