.\"  -*- nroff -*-
.\"
.\" ldverify.1
.\"
.\" Man page created from source and usage information by 
.\" Cesare Falco <c.falco@ubuntu.com>, August 2008
.\"
.TH LDVERIFY 1 2015-07-22 0.164 "MAME laserdisc data checker"
.\"
.\" NAME chapter
.SH NAME
ldverify \- MAME laserdisc data checker
.\"
.\" SYNOPSIS chapter
.SH SYNOPSIS
.B ldverify \fR[\fIavifile.avi\fR|\fIchdfile.chd\fR]
.\"
.\" DESCRIPTION chapter
.SH DESCRIPTION
.B ldverify
is a tool which walks through either an AVI or CHD capture from a
laserdisc and ensures that there are no anomalies lurking in
the VBI data.
.SH SEE ALSO
ldresample(1), mame(6), mess(6)
