.\"  -*- nroff -*-
.\"
.\" pngcmp.1
.\"
.\" Man page created from usage info.
.\" 
.\" References
.\" http://www.mame.net/mamefaq.html
.\"
.TH PNGCMP 1 2026-02-23 0.289 "MAME PNG comparison tool"
.\"
.\" NAME chapter
.SH NAME
pngcmp \- MAME PNG comparison tool
.\"
.\" SYNOPSIS chapter
.SH SYNOPSIS
.B pngcmp
.RI [ png1 ]
.RI [ png2 ]
.RI [ out ]
.\"
.\" DESCRIPTION chapter
.SH DESCRIPTION
\fBpngcmp\fP is a tool developed to display the differences of two PNG images.
.PP
It generates an new images displaying the given PNGs side by side with an
additional image containg the differening pixels.
.\"
.\" EXAMPLES chapter
.SH EXAMPLES
.B romcmp img001.png img001a.png diff.png
.\"
.\" SEE ALSO chapter
.SH SEE ALSO
mame(6)
