.\"  -*- nroff -*-
.\"
.\" testkeys.1
.\"
.\" Man page created from source and usage information
.\" Cesare Falco <c.falco@ubuntu.com>, February 2007
.\"
.TH TESTKEYS 1 2015-07-22 0.164 "MAME SDL keycode scanner"
.\"
.\" NAME chapter
.SH NAME
testkeys \- MAME SDL keycode scanner
.\"
.\" SYNOPSIS chapter
.SH SYNOPSIS
.B testkeys
.\"
.\" DESCRIPTION chapter
.SH DESCRIPTION
Since 0.113 (SDL)MAME introduced keymap files to handle keyboards
with non\-us layouts.
.PP
This simple utility helps determining which SDL keycode is bound
to each key, thus making the process of compiling keymap files a
bit easier.
.SH SEE ALSO
mame(6), mess(6)
