/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_debugmain (void);
GtkWidget* create_memorywin (void);
GtkWidget* create_disasmwin (void);
GtkWidget* create_logwin (void);
