name: CI (Linux)

on:
  push:
    paths:
    - '.github/ci-shard-map.schema.json'
    - '.github/ci-shards/linux-clang-x64-mame-release.json'
    - '.github/ci-shards/linux-gcc-x64-tiny-release.json'
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'hash/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'
  pull_request:
    paths:
    - '.github/ci-shard-map.schema.json'
    - '.github/ci-shards/linux-clang-x64-mame-release.json'
    - '.github/ci-shards/linux-gcc-x64-tiny-release.json'
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'hash/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'

permissions:
  contents: read

jobs:
  build-linux-gcc:
    uses: ./.github/workflows/ci-shards.yml
    with:
      profiles: '[".github/ci-shards/linux-gcc-x64-tiny-release.json"]'

  build-linux-clang:
    uses: ./.github/workflows/ci-shards.yml
    with:
      profiles: '[".github/ci-shards/linux-clang-x64-mame-release.json"]'
