name: CI (macOS)

on:
  push:
    paths:
    - '.github/ci-shard-map.schema.json'
    - '.github/ci-shards/macos-clang-arm64-mame-release.json'
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'
  pull_request:
    paths:
    - '.github/ci-shard-map.schema.json'
    - '.github/ci-shards/macos-clang-arm64-mame-release.json'
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'

permissions:
  contents: read

jobs:
  build-macos-clang-arm64:
    uses: ./.github/workflows/ci-shards.yml
    with:
      profiles: '[".github/ci-shards/macos-clang-arm64-mame-release.json"]'
