name: CI (Windows)

on:
  push:
    paths:
    - '.github/ci-shard-map.schema.json'
    - '.github/ci-shards/windows-clang-arm64-mame-release.json'
    - '.github/ci-shards/windows-clang-x64-tiny-release.json'
    - '.github/ci-shards/windows-gcc-x64-mame-release.json'
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'
  pull_request:
    paths:
    - '.github/ci-shard-map.schema.json'
    - '.github/ci-shards/windows-clang-arm64-mame-release.json'
    - '.github/ci-shards/windows-clang-x64-tiny-release.json'
    - '.github/ci-shards/windows-gcc-x64-mame-release.json'
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'

permissions:
  contents: read

jobs:
  build-windows-gcc-x64:
    uses: ./.github/workflows/ci-shards.yml
    with:
      profiles: '[".github/ci-shards/windows-gcc-x64-mame-release.json"]'

  build-windows-clang-x64:
    uses: ./.github/workflows/ci-shards.yml
    with:
      profiles: '[".github/ci-shards/windows-clang-x64-tiny-release.json"]'

  build-windows-clang-arm64:
    uses: ./.github/workflows/ci-shards.yml
    with:
      profiles: '[".github/ci-shards/windows-clang-arm64-mame-release.json"]'
