name: Style Check

on:
  pull_request:
    paths:
    - '.github/workflows/**'
    - 'src/**.cpp'
    - 'src/**.h'

jobs:
  stylecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        run: echo "changed_files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | xargs)" >> $GITHUB_OUTPUT

      - name: Run style check
        id: style-check
        run: |
          python3 scripts/build/style.py ${{ steps.changed-files.outputs.changed_files }}
